name: Run Jest Test Login

on: push 

jobs: 

  jest-test-login:

    runs on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: action/checkout@v3

    - name: Setup Node.js
      uses: action/setup-node@v2
  
      with: 
        node-version: '14'
    - name: Install npm dependencies
      run: npm install

    - name: Run Jest Test login
      run: npx jest SignUp.spec.ts 