name: Run Jest Tests  SignUp

on: push
    

jobs:

  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
            node-version: '14'
    - name: Install npm dependencies
      run: npm install

    - name: Run Jest Test login
      run: npx jest userSignUp.spec.ts 


    # - name: Run Jest Test login
    #   run: npx jest login.spec.ts 

    # - name: Run Jest Test create tour
    #   run: npx jest createTour.spec.ts 

